/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Heshan
 */
public class of_password extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs =null;
    ResultSet rs2 =null;
    
    String current_of_id,id;
    
    public of_password() {
        initComponents();
        
        conn=DBconnection.connect();
        tableload();
        
        eye_icone.setVisible(false);
//         pt.setVisible(false);
    }
    
    
    
    
     
     

      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eye_icone1 = new javax.swing.JLabel();
        eye_icone = new javax.swing.JLabel();
        hotel_id = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        hidden_id = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/resort1.jpg"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 10, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Hotel Id");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Password");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 63, -1));

        eye_icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/icons8-show-password-16.png"))); // NOI18N
        eye_icone1.setPreferredSize(new java.awt.Dimension(18, 18));
        eye_icone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_icone1MouseClicked(evt);
            }
        });
        jPanel6.add(eye_icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 20, 30));

        eye_icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/icons8-eye-16.png"))); // NOI18N
        eye_icone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_iconeMouseClicked(evt);
            }
        });
        jPanel6.add(eye_icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 20, 30));
        jPanel6.add(hotel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 13, 220, 30));
        jPanel6.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 220, 30));

        hidden_id.setText("id");
        jPanel6.add(hidden_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 51, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 370, -1));

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Change OFFICER Password ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update();
//        tablepw.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       hotel_id.setText("");
        pw.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         home hm = new home(); 
         hm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void eye_icone1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_icone1MouseClicked
        // TODO add your handling code here:
        
        pw.setEchoChar((char)0);
        eye_icone1.setVisible(false);
        eye_icone.setVisible(true);
    }//GEN-LAST:event_eye_icone1MouseClicked

    private void eye_iconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_iconeMouseClicked
        // TODO add your handling code here:
        
         pw.setEchoChar('*');
          eye_icone.setVisible(false);
        eye_icone1.setVisible(true);
       
    }//GEN-LAST:event_eye_iconeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(of_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(of_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(of_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(of_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new of_password().setVisible(true);
            }
        });
        
        
        
        
        
    }
    
    
     public void tableload(){
//          conn=DBconnection.connect();
         
         
         
          Statement stmt;
       
         try {
            stmt = conn.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM current_officer");
            while(rs.next()){
//          
             current_of_id=rs.getString("hotel_id");
//           
           }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
         
         
         
         
        try {
//            String sql= "SELECT id AS ID ,username AS User_Name ,password AS Password FROM officer_password";
            String sql= "SELECT id, hotel_id, password FROM officer_password where hotel_id='"+current_of_id+"' ";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
//            tablep.setModel(DbUtils.resultSetToTableModel(rs2));
            
            
               while (rs.next()) {
               
             id=(rs.getString("id"));
             
             hotel_id.setText(rs.getString("hotel_id"));
             pw.setText(rs.getString("password"));
             
             
//                Object source = e.getSource();
//                if (source.equals(euro)){
//                     startcur.setIcon(new ImageIcon("C:\\Users\\Russel\\Desktop\\1.gif"));
             
//                }


//    ImageIcon image = new ImageIcon(getClass().getResource("/icons8-show-password-16"));
////             String imagename="icons8-show-password-16";
////                   ImageIcon icon = new ImageIcon(imagename);
////                   icon.getImage().flush();
//                   eye_icone.setIcon(image);


             
             
            }
          
             
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
     
     
           public void tabledata(){
//         int r=tablep.getSelectedRow();
//         String id =tablep.getValueAt(0, 0).toString();
//        String username =tablep.getValueAt(0, 1).toString();
//         String password =tablep.getValueAt(0, 2).toString();
         
//         uname.setText(username);
//         pw.setText(password);
     }
      
      
        public void update(){
         String hotelId=hotel_id.getText();
         String password=pw.getText();
         
                Session s= connection.Controller.getSessionFactory().openSession();
                Transaction tr= s.beginTransaction();
                pojos.OfficerPassword offp= (pojos.OfficerPassword)s.load(pojos.OfficerPassword.class, Integer.parseInt(id));
                offp.setPassword(password);
                
                s.update(offp);
                tr.commit();
                System.out.println("Updated");
                
                
                Session s2= connection.Controller.getSessionFactory().openSession();
                Transaction tr2= s2.beginTransaction();
                pojos.CurrentOfficer coffp= (pojos.CurrentOfficer)s2.load(pojos.CurrentOfficer.class,1);
                coffp.setPassword(password);
                
                s2.update(coffp);
                tr2.commit();
                System.out.println("Updated2");
                
                
                 JOptionPane.showMessageDialog(null, "Password Successfully Updated ");
                 
                 
                 
                 
         
         
         
         
//         try {
//           
//            
//             String sql1 ="UPDATE officer_password SET password='"+password+"' where id='"+id+"'";
////           
//            pst= conn.prepareStatement(sql1);
//            pst.execute();
//            
//            String sql2 ="UPDATE current_officer SET password='"+password+"' ";
////           
//            pst= conn.prepareStatement(sql2);
//            pst.execute();
//            
//            
//            
//            
//            JOptionPane.showMessageDialog(null, "Password Successfully Updated ");
//            
//            home hm = new home(); 
//            hm.setVisible(true);
//            this.dispose();
//            
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null,e);
//        }
         tableload();
     }
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eye_icone;
    private javax.swing.JLabel eye_icone1;
    private javax.swing.JLabel hidden_id;
    private javax.swing.JTextField hotel_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField pw;
    // End of variables declaration//GEN-END:variables
}
