/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnection;
import codes.Model;
import java.awt.Image;
import java.awt.List;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class officer_sign_up extends javax.swing.JFrame {
    
    
    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs =null;
    
    ArrayList<String> of_id_list=new ArrayList<String>(); 
    
    

    
    public officer_sign_up() {
        initComponents();
        
          conn=DBconnection.connect();
          
          
          
          
           
    }

   
     public void attache(){
         //image 
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txt_filename.setText(filename);
       Image getAbsolutePath =null;
       ImageIcon icon =new ImageIcon(filename);
       Image image = icon.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(),Image.SCALE_SMOOTH);
       photo.setIcon(icon);
        
    }
     
      public static boolean isValid(String email)
    {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                            "[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                            "A-Z]{2,7}$";
                              
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        pword = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        oldpw = new javax.swing.JPasswordField();
        submit_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        hotid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_filename = new javax.swing.JTextField();
        Attach = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        old_hot_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/resort1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 68));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User name :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail Address:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Old Officer Password:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));
        jPanel5.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 177, -1));
        jPanel5.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 177, -1));
        jPanel5.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 177, -1));
        jPanel5.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 177, -1));
        jPanel5.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 177, -1));
        jPanel5.add(oldpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 177, -1));

        submit_btn.setBackground(new java.awt.Color(0, 0, 0));
        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel5.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 81, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hotel Id:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel5.add(hotid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 177, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Image:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel5.add(txt_filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 177, -1));

        Attach.setBackground(new java.awt.Color(0, 0, 0));
        Attach.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Attach.setForeground(new java.awt.Color(255, 255, 255));
        Attach.setText("Attach");
        Attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachActionPerformed(evt);
            }
        });
        jPanel5.add(Attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel5.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, 60));
        jPanel5.add(old_hot_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 177, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Old Officer Hotel Id:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Security Question");
        jButton1.setPreferredSize(new java.awt.Dimension(121, 23));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 247, -1, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 50));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Officer Sign Up");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
      
       
//        officer_sign_up(int q1, int q2, int q3, String ans1, String ans2, String ans3) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
        String q1 = null,q2 = null,q3 = null,a1 = null,a2 = null,a3 = null;
        
        try {
            
            
            Statement stmt = conn.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM temquestion");
            while(rs.next()){
//          
             q1=rs.getString("question1");
             q2=rs.getString("question2");
             q3=rs.getString("question3");
             a1=rs.getString("ans1");
             a2=rs.getString("ans2");
             a3=rs.getString("ans3");
             
             
//           
           }
            
            
        } catch (Exception e) {
        }
        
        
        
          String hoid,fname1,uname1,paword1,mobile1,email1,repano1,oldpw1,oldHotId;
          
          
           String image =txt_filename.getText();
       image=image.replace("\\","\\\\");
          
        
        hoid=hotid.getText();
        fname1= fname.getText();
        uname1=uname.getText();
        paword1=pword.getText();
        mobile1=mobile.getText();
        email1=email.getText();
        oldpw1=oldpw.getText();
        oldHotId=old_hot_id.getText();
        
        if (hoid.isEmpty() || fname1.isEmpty() || uname1.isEmpty() || paword1.isEmpty() || mobile1.isEmpty() || email1.isEmpty() || oldHotId.isEmpty()
                || oldpw1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill the all fields!" );
        }else{
            if (isValid(email1)) {
                
            
        
        

         
         Statement stmt;
       String password2 = null;
       
      
         try {
            stmt = conn.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM officer_password where hotel_id ='"+oldHotId+"'");
            while(rs.next()){
//          
             password2=rs.getString("password");
             
             
//           
           }
            
            
            
              try {
                  stmt = conn.createStatement();
                  
                  ResultSet rs2=stmt.executeQuery("SELECT * FROM officer_password");
            while(rs2.next()){
//          
             of_id_list.add(rs2.getString("hotel_id"));
            
        }
                  
                  
              } catch (SQLException ex) {
                  Logger.getLogger(officer_sign_up.class.getName()).log(Level.SEVERE, null, ex);
              }
            
         } catch (SQLException ex) {
                  Logger.getLogger(officer_sign_up.class.getName()).log(Level.SEVERE, null, ex);
              }
         
         
       if(oldpw1.equals(password2)){
           
           if (!of_id_list.contains(hoid)) {
               
        
            try {
                   String sql ="INSERT INTO officer_details(hotel_id,name,contact,mail,image)VALUES ('"+hoid+"','"+fname1+"','"+mobile1+"','"+email1+"','"+image+"')";
                   pst= conn.prepareStatement(sql);
                   pst.execute();


                     String sql1 ="INSERT INTO officer_password(username,hotel_id,password,question1,question2,question3,ans1,ans2,ans3)VALUES ('"+uname1+"','"+hoid+"','"+paword1+"','"+q1+"','"+q2+"','"+q3+"','"+a1+"','"+a2+"','"+a3+"')";
                   pst= conn.prepareStatement(sql1);
                   pst.execute();
                   
                   
                   String sql2 ="UPDATE current_officer SET hotel_id='"+hoid+"',username='"+uname1+"',password='"+paword1+"'";
                 pst= conn.prepareStatement(sql2);
                 pst.execute();
                   
                   JOptionPane.showMessageDialog(null, "Welcome New Officer. ");
                   home hm = new home(); 
                   hm.setVisible(true);
                   this.dispose();


               } catch (Exception e) {
                   JOptionPane.showMessageDialog(null,e);
               }
            
                }else{
                JOptionPane.showMessageDialog(null, "Your Hotel Id already in use" );
           }
        
        }
       
       else{
            JOptionPane.showMessageDialog(null, "Please check officer Id and password" );
        }
       
       
         }else{
                 JOptionPane.showMessageDialog(null, "Please enter valid email" );
            }
            
       }
       
        
    }//GEN-LAST:event_submit_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login lg= new login(); 
            lg.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachActionPerformed
        
        attache();
    }//GEN-LAST:event_AttachActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        SQuestion sq= new SQuestion(); 
            sq.setVisible(true);
            
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(officer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(officer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(officer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(officer_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new officer_sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attach;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hotid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField old_hot_id;
    private javax.swing.JPasswordField oldpw;
    private javax.swing.JLabel photo;
    private javax.swing.JPasswordField pword;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField txt_filename;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
