/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnection;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.hibernate.CacheMode;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Projection;
import org.hibernate.criterion.Projections;




/**
 *
 * @author Heshan
 */
public class Payment extends javax.swing.JFrame {

    
    Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs =null;
    
    
    
    
    
    
    
    
    
    public Payment() {
        initComponents();
         conn=DBconnection.connect();
         
         tableload();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        dd = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        panelRound1 = new inf.PanelRound();
        name_label = new javax.swing.JLabel();
        roomNo_lable1 = new javax.swing.JLabel();
        package_lable = new javax.swing.JLabel();
        payment_id_lable = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        amount_lable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        payment_id_lable1 = new javax.swing.JLabel();
        roomNo_lable2 = new javax.swing.JLabel();
        name_label1 = new javax.swing.JLabel();
        package_lable1 = new javax.swing.JLabel();
        amount_lable1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        income = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        payment_details = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dd.setBackground(new java.awt.Color(255, 255, 255));
        dd.setPreferredSize(new java.awt.Dimension(1024, 100));
        dd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Queen Mery Resort");
        dd.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jPanel1.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 0, 700, 29));

        panelRound1.setBackground(new java.awt.Color(0, 51, 102));
        panelRound1.setMinimumSize(new java.awt.Dimension(350, 625));
        panelRound1.setPreferredSize(new java.awt.Dimension(350, 600));
        panelRound1.setRoundTopRight(100);

        name_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_label.setForeground(new java.awt.Color(255, 255, 255));
        name_label.setText("Customer Name ");

        roomNo_lable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomNo_lable1.setForeground(new java.awt.Color(255, 255, 255));
        roomNo_lable1.setText("Room No            ");

        package_lable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        package_lable.setForeground(new java.awt.Color(255, 255, 255));
        package_lable.setText("Package     ");

        payment_id_lable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payment_id_lable.setForeground(new java.awt.Color(255, 255, 255));
        payment_id_lable.setText("Payment Id  ");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(180, 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        amount_lable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amount_lable.setForeground(new java.awt.Color(255, 255, 255));
        amount_lable.setText("Amount        ");

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Summary");

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        payment_id_lable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payment_id_lable1.setForeground(new java.awt.Color(255, 255, 255));
        payment_id_lable1.setText("Payment Id       :");

        roomNo_lable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomNo_lable2.setForeground(new java.awt.Color(255, 255, 255));
        roomNo_lable2.setText("Room No         :  ");

        name_label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_label1.setForeground(new java.awt.Color(255, 255, 255));
        name_label1.setText("Customer Name : ");

        package_lable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        package_lable1.setForeground(new java.awt.Color(255, 255, 255));
        package_lable1.setText("Package           :");

        amount_lable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amount_lable1.setForeground(new java.awt.Color(255, 255, 255));
        amount_lable1.setText("Amount           : ");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(amount_lable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(package_lable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(name_label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(payment_id_lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(roomNo_lable2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(payment_id_lable)
                                    .addComponent(roomNo_lable1)
                                    .addComponent(name_label)
                                    .addComponent(package_lable)
                                    .addComponent(amount_lable)))))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(payment_id_lable)
                        .addGap(40, 40, 40)
                        .addComponent(roomNo_lable1)
                        .addGap(39, 39, 39)
                        .addComponent(name_label)
                        .addGap(41, 41, 41)
                        .addComponent(package_lable)
                        .addGap(44, 44, 44)
                        .addComponent(amount_lable))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(payment_id_lable1)
                        .addGap(40, 40, 40)
                        .addComponent(roomNo_lable2)
                        .addGap(39, 39, 39)
                        .addComponent(name_label1)
                        .addGap(41, 41, 41)
                        .addComponent(package_lable1)
                        .addGap(44, 44, 44)
                        .addComponent(amount_lable1)))
                .addGap(104, 104, 104)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 346, 784));

        jPanel3.setBackground(new java.awt.Color(93, 87, 255));
        jPanel3.setForeground(new java.awt.Color(157, 40, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment History");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Officers Only");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Total Income  :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, 20));

        income.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        income.setForeground(new java.awt.Color(255, 255, 255));
        income.setText("amount");
        jPanel3.add(income, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 100, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 39, 1030, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 269));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        payment_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        payment_details.setGridColor(new java.awt.Color(102, 0, 0));
        payment_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payment_detailsMouseClicked(evt);
            }
        });
        payment_details.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                payment_detailsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(payment_details);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 919;
        gridBagConstraints.ipady = 431;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(19, 45, 19, 29);
        jPanel5.add(jScrollPane1, gridBagConstraints);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 289, 1024, 500));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 3, 2);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void payment_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment_detailsMouseClicked
        // TODO add your handling code here:
        
        getTableData();
    }//GEN-LAST:event_payment_detailsMouseClicked

    private void payment_detailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payment_detailsKeyReleased
        // TODO add your handling code here:
        getTableData();
    }//GEN-LAST:event_payment_detailsKeyReleased

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
      
            home home= new home(); 
            home.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_backMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
                
                
                
                
              
                
                
            }
        });
    }
    
    
     public void tableload(){
        try {
            String sql= "SELECT id AS ID ,package AS 'Package' ,customer AS 'Customer Name',room_no AS 'Room No' ,payment_id AS 'Payment_Id',payment AS 'Payment' FROM payment";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
           payment_details.setModel(DbUtils.resultSetToTableModel(rs));
           
           
//           float amount=0f;
//           String sql2="SELECT  payment FROM payment";
//           pst=conn.prepareStatement(sql2);
//           rs=pst.executeQuery();
//           
//           
//            while (rs.next()) {                
//                amount+=Float.parseFloat(rs.getString("payment"));
//            }
//            income.setText(String.valueOf(amount));

//Get Total Value using Hibernate.....................................................................................................

            float tot_amount=0f;
        Session s= connection.Controller.getSessionFactory().openSession();
            Criteria c= s.createCriteria(pojos.Payment.class);
               List<pojos.Payment> pay =c.list();
               
               for(pojos.Payment amt:pay){
                   System.out.println(Float.parseFloat(amt.getPayment()));
                   tot_amount+=Float.parseFloat(amt.getPayment());
                   
               }
               System.out.println(tot_amount);
               income.setText(String.valueOf(tot_amount));
        




           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
     
     public void getTableData(){
         
         int r =payment_details.getSelectedRow();
         
          String package_name =payment_details.getValueAt(r, 1).toString();
          String room_no =payment_details.getValueAt(r, 2).toString();
          String customer_name =payment_details.getValueAt(r, 3).toString();
          String pay_id =payment_details.getValueAt(r, 4).toString();
          String payment_amount =payment_details.getValueAt(r, 5).toString();
         
          
          payment_id_lable.setText(pay_id);
          package_lable.setText(package_name);
          roomNo_lable1.setText(room_no);
          name_label.setText(customer_name);
          amount_lable.setText(payment_amount);
         
     }
    
    
    
    

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_lable;
    private javax.swing.JLabel amount_lable1;
    private javax.swing.JButton back;
    private javax.swing.JPanel dd;
    private javax.swing.JLabel income;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label1;
    private javax.swing.JLabel package_lable;
    private javax.swing.JLabel package_lable1;
    private inf.PanelRound panelRound1;
    private javax.swing.JTable payment_details;
    private javax.swing.JLabel payment_id_lable;
    private javax.swing.JLabel payment_id_lable1;
    private javax.swing.JLabel roomNo_lable1;
    private javax.swing.JLabel roomNo_lable2;
    // End of variables declaration//GEN-END:variables





}
