
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Message;
import javax.swing.JOptionPane;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;


/**
 *
 * @author Heshan
 */
public class resetPw extends javax.swing.JFrame {

    
      Connection conn=null;
    PreparedStatement pst =null;
    ResultSet rs =null;
    /**
     * Creates new form resetPw
     */
    public resetPw() {
        initComponents();
         conn=DBconnection.connect();
         contactPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        qt1 = new javax.swing.JLabel();
        qt2 = new javax.swing.JLabel();
        qt3 = new javax.swing.JLabel();
        ansT3 = new javax.swing.JTextField();
        hidTextF = new javax.swing.JTextField();
        ansT2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ansT1 = new javax.swing.JTextField();
        eye_icone1 = new javax.swing.JLabel();
        eye_icone = new javax.swing.JLabel();
        passwordTestF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hidTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        contactPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sendEmail = new javax.swing.JTextField();
        eye_icone2 = new javax.swing.JLabel();
        eye_icone3 = new javax.swing.JLabel();
        emailPassword = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        email_showBtn = new javax.swing.JToggleButton();
        jPanel4 = new inf.PanelRound();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qt1.setForeground(new java.awt.Color(0, 0, 51));
        qt1.setText("questoin 1");
        jPanel2.add(qt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        qt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qt2.setForeground(new java.awt.Color(0, 0, 51));
        qt2.setText("question2");
        jPanel2.add(qt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        qt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qt3.setForeground(new java.awt.Color(0, 0, 51));
        qt3.setText("question 3");
        jPanel2.add(qt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel2.add(ansT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, -1));
        jPanel2.add(hidTextF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 170, -1));
        jPanel2.add(ansT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Hotel ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel2.add(ansT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, -1));

        eye_icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/icons8-show-password-16.png"))); // NOI18N
        eye_icone1.setPreferredSize(new java.awt.Dimension(18, 18));
        eye_icone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_icone1MouseClicked(evt);
            }
        });
        jPanel2.add(eye_icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 20, 30));

        eye_icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/icons8-eye-16.png"))); // NOI18N
        eye_icone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_iconeMouseClicked(evt);
            }
        });
        jPanel2.add(eye_icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 20, 30));
        jPanel2.add(passwordTestF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Hotel ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 30));
        jPanel2.add(hidTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Find Password");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Back to Login");
        jButton3.setPreferredSize(new java.awt.Dimension(123, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Reset Password");
        jButton4.setPreferredSize(new java.awt.Dimension(123, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        contactPanel.setBackground(new java.awt.Color(255, 255, 255));
        contactPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Your Emal :");
        contactPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Password :");
        contactPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, 20));
        contactPanel.add(sendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 11, 137, -1));

        eye_icone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/icons8-show-password-16.png"))); // NOI18N
        eye_icone2.setPreferredSize(new java.awt.Dimension(18, 18));
        eye_icone2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_icone2MouseClicked(evt);
            }
        });
        contactPanel.add(eye_icone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 39, 20, 30));

        eye_icone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/icons8-eye-16.png"))); // NOI18N
        eye_icone3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye_icone3MouseClicked(evt);
            }
        });
        contactPanel.add(eye_icone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 39, 20, 30));
        contactPanel.add(emailPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 42, 138, -1));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Heshan\\Documents\\Hotel_Reservation_System\\src\\Resourses\\reset-password.png")); // NOI18N
        jToggleButton1.setText("Request Password Reset");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        contactPanel.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel2.add(contactPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 310, 140));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Contact Technical  officer");
        jLabel4.setMinimumSize(new java.awt.Dimension(155, 13));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 23));

        email_showBtn.setBackground(new java.awt.Color(255, 255, 255));
        email_showBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Heshan\\Documents\\Hotel_Reservation_System\\src\\Resourses\\email.png")); // NOI18N
        email_showBtn.setMaximumSize(new java.awt.Dimension(52, 25));
        email_showBtn.setMinimumSize(new java.awt.Dimension(49, 30));
        email_showBtn.setPreferredSize(new java.awt.Dimension(40, 25));
        email_showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_showBtnActionPerformed(evt);
            }
        });
        jPanel2.add(email_showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 390));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reset Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getQA();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        checkAns();
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        resetPW();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void eye_icone1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_icone1MouseClicked
        // TODO add your handling code here:

        passwordTestF.setEchoChar((char)0);
        eye_icone1.setVisible(false);
        eye_icone.setVisible(true);
    }//GEN-LAST:event_eye_icone1MouseClicked

    private void eye_iconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_iconeMouseClicked
        // TODO add your handling code here:

        passwordTestF.setEchoChar('*');
        eye_icone.setVisible(false);
        eye_icone1.setVisible(true);

    }//GEN-LAST:event_eye_iconeMouseClicked

    private void email_showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_showBtnActionPerformed
        // TODO add your handling code here:
        if(email_showBtn.isSelected()){
            contactPanel.setVisible(true);
        }else{
            contactPanel.setVisible(false);
        }
        
    }//GEN-LAST:event_email_showBtnActionPerformed

    private void eye_icone2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_icone2MouseClicked
        emailPassword.setEchoChar((char)0);
        eye_icone2.setVisible(false);
        eye_icone3.setVisible(true);
    }//GEN-LAST:event_eye_icone2MouseClicked

    private void eye_icone3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_icone3MouseClicked
        // TODO add your handling code here:
         emailPassword.setEchoChar((char)'*');
        eye_icone2.setVisible(true);
        eye_icone3.setVisible(false);
    }//GEN-LAST:event_eye_icone3MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (!hidTextF.getText().toString().isEmpty() && !sendEmail.getText().toString().isEmpty() && !emailPassword.getText().toString().isEmpty()) {
             if (contactOfficer()==true) {
            JOptionPane.showMessageDialog(null,"Password Reset Request Sent Successfully");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Please Insert Hotel ID Email and Pasword! ");
        }
        
      
         
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetPw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetPw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansT1;
    private javax.swing.JTextField ansT2;
    private javax.swing.JTextField ansT3;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JPasswordField emailPassword;
    private javax.swing.JToggleButton email_showBtn;
    private javax.swing.JLabel eye_icone;
    private javax.swing.JLabel eye_icone1;
    private javax.swing.JLabel eye_icone2;
    private javax.swing.JLabel eye_icone3;
    private javax.swing.JTextField hidTextF;
    private javax.swing.JTextField hidTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private inf.PanelRound jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField passwordTestF;
    private javax.swing.JLabel qt1;
    private javax.swing.JLabel qt2;
    private javax.swing.JLabel qt3;
    private javax.swing.JTextField sendEmail;
    // End of variables declaration//GEN-END:variables

     String hotelID_1,hotelID_2,question1 = null,question2 = null,question3 = null,answer1,answer2,answer3,password;
     
     String hotelID_2_2,question1_2 = null,question2_2 = null,question3_2 = null,answer1_2,answer2_2,answer3_2,password_2;
     
     
     
     
    private void getQA() {
       boolean hasRow = false;
       
        
        hotelID_1= hidTextField1.getText().toString();
        if (!hotelID_1.isEmpty()) {
            
       
        
        Statement stmt;
        try {
            stmt = conn.createStatement();
            ResultSet rs=stmt.executeQuery("SELECT * FROM assistante_password where hotel_id ='"+hotelID_1+"'");
            while(rs.next()){
             hotelID_1 =rs.getString("hotel_id");
             
             password =rs.getString("password");
             
             question1=rs.getString("question1");
             question2=rs.getString("question2");
             question3=rs.getString("question3");
             
             answer1=rs.getString("ans1").toLowerCase();
             answer2=rs.getString("ans2").toLowerCase();
             answer3=rs.getString("ans3").toLowerCase();
             
               hasRow = true;
    
                    
           }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
         
        
    if(!hasRow){
                                       
              Statement stmt2;
        try {
            stmt2 = conn.createStatement();
            ResultSet rs=stmt2.executeQuery("SELECT * FROM officer_password where hotel_id ='"+hotelID_1+"'");
            boolean hasrow =false;
            while(rs.next()){
             hotelID_1 =rs.getString("hotel_id");
             
             password_2 =rs.getString("password");
             
             question1_2=rs.getString("question1");
             question2_2=rs.getString("question2");
             question3_2=rs.getString("question3");
             
             answer1_2=rs.getString("ans1").toLowerCase();
             answer2_2=rs.getString("ans2").toLowerCase();
             answer3_2=rs.getString("ans3").toLowerCase();
             
             qt1.setText(question1_2);
             qt2.setText(question2_2);
             qt3.setText(question3_2);
             
             hasrow=true;
                    
           }
            if(!hasrow){
                System.out.println("Check your Hotel Id again!");
                JOptionPane.showMessageDialog(null,"Check your Hotel Id again!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
                     
                     
                 
    } else {
        
        qt1.setText(question1);
        qt2.setText(question2);
        qt3.setText(question3);
        
    }
     
    
    }else{
            JOptionPane.showMessageDialog(null, "Please enter Hotel Id");
        }
        
    }

    private void checkAns() {
        String a1,a2,a3;
       a1= ansT1.getText().toLowerCase();
       a2= ansT2.getText().toLowerCase();
       a3= ansT3.getText().toLowerCase();
       
        if (a1.isEmpty() || a2.isEmpty() || a3.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please fill the all answers!");
            
        }else{
            
            
            
       
       
       if(a1.equals(answer1) && a2.equals(answer2) && a3.equals(answer3)){
           
           hidTextF.setText(hotelID_1);
           
           passwordTestF.setText(password);
           passwordTestF.setEchoChar((char)'*');
       }else if(a1.equals(answer1_2) && a2.equals(answer2_2) && a3.equals(answer3_2)){
           
             hidTextF.setText(hotelID_1);
           
           passwordTestF.setText(password_2);
           passwordTestF.setEchoChar((char)'*');
       }else{
           
           JOptionPane.showMessageDialog(null,"Check your Answers again!");
       }
        
         }
        
    }

    private void resetPW() {
        String hotelID=hidTextF.getText().toString();
        String newpw=passwordTestF.getText().toString();
        
           
         try {
           
            
             String sql1 ="UPDATE officer_password SET password='"+newpw+"' where hotel_id='"+hotelID+"'";
//           
            pst= conn.prepareStatement(sql1);
            pst.execute();

            
            String sql2 ="UPDATE assistante_password SET password='"+newpw+"' where hotel_id='"+hotelID+"'";
//           
            pst= conn.prepareStatement(sql2);
            pst.execute();
            
            
            
            
            JOptionPane.showMessageDialog(null, "Password successfully reset");
            
            login lg = new login(); 
            lg.setVisible(true);
            this.dispose();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
             
    }
    
    
    private boolean contactOfficer(){
        
//        Properties properties=new Properties();
//        properties.put("mail.smtp.starttls.enable", "true");

        Properties props=new Properties();

        props.put("mail.smtp.user","username"); 
props.put("mail.smtp.host", "smtp.gmail.com"); 
props.put("mail.smtp.port", "25"); 
props.put("mail.debug", "true"); 
props.put("mail.smtp.auth", "true"); 
props.put("mail.smtp.starttls.enable","true"); 
props.put("mail.smtp.EnableSSL.enable","true");

props.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");   
props.setProperty("mail.smtp.socketFactory.fallback", "false");   
props.setProperty("mail.smtp.port", "465");   
props.setProperty("mail.smtp.socketFactory.port", "465"); 

        
        boolean MSG=false;
        
           
           String sendemail=sendEmail.getText().toString();
           String password=emailPassword.getText().toString();
           String tomail="hrworksdot@gmail.com";
           String subject="Password Changing";
           String msg=hidTextF.getText().toString()+" need to change their password please contact "+ hidTextF.getText().toString() ;
           
//            properties.put("mail.smtp.auth", "true");
//          properties.put("mail.smtp.host", "smtp.gmail.com");
//           properties.put("mail.smtp.port", "587");
//           properties.put("mail.smtp.ssl.trust", "*");
           
           Session session= Session.getInstance(props, new javax.mail.Authenticator() {
               
               protected PasswordAuthentication getPasswordAuthentication(){
                   
                   return new PasswordAuthentication(sendemail, password);
               }
            });
           
           try {
            
               MimeMessage message = new MimeMessage(session);
               message.setFrom(new InternetAddress(sendemail));
               message.addRecipient(Message.RecipientType.TO, new InternetAddress(tomail));
               message.setSubject(subject);
               message.setText(msg);
                
               Transport.send(message);
               MSG=true;
               
               
               
        } catch (Exception e) {
               System.out.println(e);
        }
          
           
           return MSG;
    }
    
    
}
