package pojos;
// Generated Aug 7, 2022 12:12:03 AM by Hibernate Tools 4.3.1



/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private Integer id;
     private int roomNo;
     private String name;
     private String contact;
     private String mail;
     private int members;
     private String address;
     private String package_;
     private String paymentId;
     private float payment;

    public Clients() {
    }

	
    public Clients(int roomNo, String name, String contact, String mail, int members, String address, String package_, float payment) {
        this.roomNo = roomNo;
        this.name = name;
        this.contact = contact;
        this.mail = mail;
        this.members = members;
        this.address = address;
        this.package_ = package_;
        this.payment = payment;
    }
    public Clients(int roomNo, String name, String contact, String mail, int members, String address, String package_, String paymentId, float payment) {
       this.roomNo = roomNo;
       this.name = name;
       this.contact = contact;
       this.mail = mail;
       this.members = members;
       this.address = address;
       this.package_ = package_;
       this.paymentId = paymentId;
       this.payment = payment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(int roomNo) {
        this.roomNo = roomNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public int getMembers() {
        return this.members;
    }
    
    public void setMembers(int members) {
        this.members = members;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPackage_() {
        return this.package_;
    }
    
    public void setPackage_(String package_) {
        this.package_ = package_;
    }
    public String getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }
    public float getPayment() {
        return this.payment;
    }
    
    public void setPayment(float payment) {
        this.payment = payment;
    }




}


