package pojos;
// Generated Aug 7, 2022 12:12:03 AM by Hibernate Tools 4.3.1



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int roomNo;
     private String dateIn;
     private String dateOut;
     private String package_;
     private String miniBar;
     private String pool;
     private String spa;

    public Reservation() {
    }

    public Reservation(String name, int roomNo, String dateIn, String dateOut, String package_, String miniBar, String pool, String spa) {
       this.name = name;
       this.roomNo = roomNo;
       this.dateIn = dateIn;
       this.dateOut = dateOut;
       this.package_ = package_;
       this.miniBar = miniBar;
       this.pool = pool;
       this.spa = spa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(int roomNo) {
        this.roomNo = roomNo;
    }
    public String getDateIn() {
        return this.dateIn;
    }
    
    public void setDateIn(String dateIn) {
        this.dateIn = dateIn;
    }
    public String getDateOut() {
        return this.dateOut;
    }
    
    public void setDateOut(String dateOut) {
        this.dateOut = dateOut;
    }
    public String getPackage_() {
        return this.package_;
    }
    
    public void setPackage_(String package_) {
        this.package_ = package_;
    }
    public String getMiniBar() {
        return this.miniBar;
    }
    
    public void setMiniBar(String miniBar) {
        this.miniBar = miniBar;
    }
    public String getPool() {
        return this.pool;
    }
    
    public void setPool(String pool) {
        this.pool = pool;
    }
    public String getSpa() {
        return this.spa;
    }
    
    public void setSpa(String spa) {
        this.spa = spa;
    }




}


