package pojos;
// Generated Aug 7, 2022 12:12:03 AM by Hibernate Tools 4.3.1



/**
 * Temquestion generated by hbm2java
 */
public class Temquestion  implements java.io.Serializable {


     private Integer id;
     private String question1;
     private String question2;
     private String question3;
     private String ans1;
     private String ans2;
     private String ans3;

    public Temquestion() {
    }

    public Temquestion(String question1, String question2, String question3, String ans1, String ans2, String ans3) {
       this.question1 = question1;
       this.question2 = question2;
       this.question3 = question3;
       this.ans1 = ans1;
       this.ans2 = ans2;
       this.ans3 = ans3;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getQuestion1() {
        return this.question1;
    }
    
    public void setQuestion1(String question1) {
        this.question1 = question1;
    }
    public String getQuestion2() {
        return this.question2;
    }
    
    public void setQuestion2(String question2) {
        this.question2 = question2;
    }
    public String getQuestion3() {
        return this.question3;
    }
    
    public void setQuestion3(String question3) {
        this.question3 = question3;
    }
    public String getAns1() {
        return this.ans1;
    }
    
    public void setAns1(String ans1) {
        this.ans1 = ans1;
    }
    public String getAns2() {
        return this.ans2;
    }
    
    public void setAns2(String ans2) {
        this.ans2 = ans2;
    }
    public String getAns3() {
        return this.ans3;
    }
    
    public void setAns3(String ans3) {
        this.ans3 = ans3;
    }




}


